#!/bin/bash
TARGET=apples
downstream=false;upstream=false
TESTDURATION=25
IPERFSERVER=192.168.0.200
SCRIPT="/home/lordberre-server/screens/ap_physcripting/./celeno_iw-snmp_forloop.sh"
ansible_check="$(ansible $TARGET -m ping | grep SUCCESS | wc -l)"
iperf3_check="$(iperf3 -c $IPERFSERVER -t 1 | grep busy | wc -l)"
iperf3log="/var/log/iperf3_wrapper.log"
if [ $(pgrep -f celeno | wc -l) -gt 1 ];then 
kill $(pgrep -f celeno) && echo Killed some leftover scripts..
else echo "no leftover scripts detected (OK)"
fi

# Start test function
start_test () {
        if [ $ansible_check -ge 1 ] && [ $iperf3_check -le 0 ];then
sleep 1
bash $SCRIPT 1> /dev/null &
ansible $TARGET -m shell -a "nohup /bin/bash $LOCALSCRIPT $IPERFSERVER &" >> $iperf3log
        else echo "Aborting because target is either unreachable ($ansible_check) or the iperf3 server is busy ($iperf3_check)" && exit 1
fi
}

# Make sure that the test is performed and not "skipped" due to the server becoming busy after we exited the first busy loop
failcheck () {
checkbusy="$(tail -1 $iperf3log | grep iperf3 | wc -l)"
busyfail=0
while [ $checkbusy -eq 1 ]; do
echo "no entry in the log, test must've failed, trying again.."
sleep $[ ( $RANDOM % 1 ) + 3]s &&
start_test
checkbusy="$(tail -1 $iperf3log | grep iperf3 | wc -l)"

# Anti fail
busyfail=$(( $busyfail + 1 ))
if [ $busyfail -ge 20 ]; then
echo "[$logtag] Giving up, since we didn't manage to access the server for over $busyfail retries. How can it be this busy?" | logger -p local5.err && break
fi
done
}

options=':u:d:hv'

while getopts $options option
do
    case $option in
        u  ) upstream=true;TARGET=${OPTARG}       ;;
        h  ) usage; exit;;
        d  ) downstream=true;TARGET=${OPTARG};;
        \? ) echo "Unknown option: -$OPTARG" >&2; exit 1;;
        :  ) echo "Missing option argument for -$OPTARG" >&2; exit 1;;
        *  ) echo "Unimplemented option: -$OPTARG" >&2; exit 1;;
    esac
done

shift $(($OPTIND - 1))

if [ $upstream = true ]; then 
# Macs have different scripts depending on direction so..
LOCALSCRIPT="/Users/testlabbet-pro/Labb-stuff/probes/mac_tcp_iperf3_client-logstash.sh"
start_test;failcheck


fi

if [ $downstream = true ]; then
# Macs have different scripts depending on direction so..
LOCALSCRIPT="/Users/testlabbet-pro/Labb-stuff/probes/mac_tcp_iperf3_client_reversed-logstash.sh"
start_test;failcheck
fi
